# Generated by Django 5.0 on 2023-12-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='media/categories/')),
            ],
        ),
    ]
