# Generated by Django 5.0 on 2023-12-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_categories_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategories_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcate', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='media/subcate/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.categories_data')),
            ],
        ),
    ]
