# Generated by Django 5.0 on 2023-12-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_subcategories_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcategories_data',
        ),
    ]
