# Generated by Django 5.0 on 2023-12-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_remove_subcategories_data_cate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='petacategories_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petacate', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='media/petacate/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.categories_data')),
                ('subcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subcategories_data')),
            ],
        ),
    ]
