# Generated by Django 5.0 on 2023-12-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_petacategories_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=5000)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('image', models.FileField(upload_to='media/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.categories_data')),
                ('petacate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.petacategories_data')),
                ('subcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subcategories_data')),
            ],
        ),
    ]
