# Generated by Django 5.0 on 2023-12-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_visiters_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visiters_data',
        ),
    ]
