# Generated by Django 5.0 on 2023-12-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_product_data_price_alter_product_data_quantity'),
        ('web_app', '0004_delete_visiters_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user_data')),
            ],
        ),
    ]
