# Generated by Django 5.0 on 2024-01-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('pro_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.cart')),
            ],
        ),
    ]
