# Generated by Django 5.0 on 2024-01-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pro_name',
            field=models.CharField(max_length=100),
        ),
    ]
