# Generated by Django 5.0 on 2024-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_alter_checkout_pro_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
